version: '3.8'
services:
  task-db:
    image: postgres:14
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: crijav
      POSTGRES_DB: taskDB
    networks:
      - crijav
networks:
  crijav:
